# Generated by Django 5.1.7 on 2026-01-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_user',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Google User'),
        ),
    ]
