# Generated by Django 5.1.7 on 2026-01-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_google_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Class Level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='exam_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exam Target'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_branches',
            field=models.CharField(blank=True, help_text='Comma-separated list of preferred branches', max_length=255, null=True, verbose_name='Preferred Branches'),
        ),
    ]
