# Generated by Django 5.1.7 on 2026-01-20 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_class_level_customuser_exam_target_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], db_index=True, default='pending', help_text='Referral status', max_length=10, verbose_name='Status')),
                ('referral_code_used', models.CharField(db_index=True, help_text='The referral code that was used', max_length=20, verbose_name='Referral Code Used')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('activated_at', models.DateTimeField(blank=True, db_index=True, help_text='When the referral was activated (referred user logged in)', null=True, verbose_name='Activated At')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('first_login', 'First Login Bonus'), ('referral_bonus', 'Referral Bonus')], db_index=True, max_length=20, verbose_name='Reward Type')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the reward (e.g., referral count, milestone reached)', verbose_name='Details')),
                ('credits_awarded', models.IntegerField(default=0, help_text='Number of room credits awarded', verbose_name='Credits Awarded')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Reward History',
                'verbose_name_plural': 'Reward Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_login_rewarded',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether the user has received their first login bonus', verbose_name='First Login Rewarded'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique code for referring other users', max_length=20, null=True, unique=True, verbose_name='Referral Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code of the user who referred this user', max_length=20, null=True, verbose_name='Referred By'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='room_credits',
            field=models.IntegerField(default=0, help_text='Available credits for creating rooms', verbose_name='Room Credits'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referrals',
            field=models.IntegerField(default=0, help_text='Total number of active referrals', verbose_name='Total Referrals'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referral_code'], name='accounts_cu_referra_4d2021_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referred_by'], name='accounts_cu_referre_29f8e0_idx'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ForeignKey(blank=True, help_text='User who was referred (null until activation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL, verbose_name='Referred User'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(help_text='User who made the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Referrer'),
        ),
        migrations.AddField(
            model_name='rewardhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_history', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'status'], name='accounts_re_referre_92276f_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referred', 'status'], name='accounts_re_referre_1e1f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_code_used'], name='accounts_re_referra_c313a8_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['-created_at'], name='accounts_re_created_3d1ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(condition=models.Q(('referred__isnull', False)), fields=('referrer', 'referred'), name='unique_referral'),
        ),
        migrations.AddIndex(
            model_name='rewardhistory',
            index=models.Index(fields=['user', '-created_at'], name='accounts_re_user_id_6fe35d_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardhistory',
            index=models.Index(fields=['reward_type', '-created_at'], name='accounts_re_reward__154330_idx'),
        ),
    ]
