# Generated by Django 5.1.7 on 2026-01-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_referral_rewardhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GUILD', 'Guild'), ('GENERAL', 'General'), ('TASK', 'Task')], db_index=True, max_length=50, verbose_name='Category')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='accounts_no_user_id_b29cd4_idx'), models.Index(fields=['category', '-created_at'], name='accounts_no_categor_953fb8_idx')],
            },
        ),
    ]
