# Generated by Django 5.1.7 on 2026-01-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('GUILD', 'Guild'), ('GENERAL', 'General'), ('TASK', 'Task'), ('SCHOLARSHIP', 'Scholarship')], db_index=True, max_length=50, verbose_name='Category'),
        ),
    ]
