# Generated by Django 5.1.7 on 2026-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_data',
            field=models.JSONField(blank=True, help_text='Additional data for the action (e.g., {"interaction_id": 1})', null=True, verbose_name='Action Data'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(blank=True, help_text='Type of action (e.g., "scholarship_apply_confirm")', max_length=50, null=True, verbose_name='Action Type'),
        ),
    ]
