# Generated by Django 5.1.7 on 2026-01-12 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Scholarship Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('provider_name', models.CharField(db_index=True, help_text='Organization providing the scholarship', max_length=255, verbose_name='Provider Name')),
                ('provider_website', models.URLField(blank=True, verbose_name='Provider Website')),
                ('scholarship_type', models.CharField(choices=[('merit_based', 'Merit Based'), ('need_based', 'Need Based'), ('sports', 'Sports'), ('minority', 'Minority'), ('disability', 'Disability'), ('research', 'Research'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Scholarship Type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in INR (null if variable)', max_digits=12, null=True, verbose_name='Scholarship Amount')),
                ('amount_description', models.CharField(blank=True, help_text='Description if amount is variable (e.g., "Up to 50,000")', max_length=255, verbose_name='Amount Description')),
                ('application_deadline', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Application Deadline')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('eligibility_rules', models.JSONField(blank=True, default=dict, help_text='Structured eligibility criteria (JSON) for rule engine', verbose_name='Eligibility Rules')),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='List of required document types', verbose_name='Required Documents')),
                ('application_instructions', models.TextField(blank=True, verbose_name='Application Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['status', 'is_active', '-application_deadline'], name='scholarship_status_68222a_idx'), models.Index(fields=['scholarship_type', 'status'], name='scholarship_scholar_1a1673_idx'), models.Index(fields=['provider_name', 'status'], name='scholarship_provide_8ac917_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20, verbose_name='Application Status')),
                ('personal_statement', models.TextField(blank=True, help_text="Student's personal statement or essay", verbose_name='Personal Statement')),
                ('additional_info', models.JSONField(blank=True, default=dict, help_text='Additional application data (flexible schema)', verbose_name='Additional Information')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Submitted At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scholarships.scholarship', verbose_name='Scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'verbose_name_plural': 'Scholarship Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('needs_more_info', 'Needs More Information')], db_index=True, max_length=20, verbose_name='Review Decision')),
                ('comments', models.TextField(blank=True, help_text='Internal review notes', verbose_name='Review Comments')),
                ('student_feedback', models.TextField(blank=True, help_text='Feedback message visible to student', verbose_name='Student Feedback')),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Reviewed At')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('reviewer', models.ForeignKey(help_text='Admin user who reviewed the application', on_delete=django.db.models.deletion.PROTECT, related_name='scholarship_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='scholarships.scholarshipapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Application Review',
                'verbose_name_plural': 'Application Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('identity_proof', 'Identity Proof'), ('income_certificate', 'Income Certificate'), ('academic_transcript', 'Academic Transcript'), ('mark_sheet', 'Mark Sheet'), ('exam_score_card', 'Exam Score Card'), ('caste_certificate', 'Caste Certificate'), ('disability_certificate', 'Disability Certificate'), ('bank_statement', 'Bank Statement'), ('recommendation_letter', 'Recommendation Letter'), ('personal_statement', 'Personal Statement'), ('other', 'Other')], db_index=True, max_length=50, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='scholarship_documents/%Y/%m/%d/', verbose_name='Document File')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255, verbose_name='File Name')),
                ('file_size', models.PositiveIntegerField(verbose_name='File Size (Bytes)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Uploaded At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarships.scholarshipapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Scholarship Document',
                'verbose_name_plural': 'Scholarship Documents',
                'ordering': ['application', 'document_type', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('min_age', 'Minimum Age'), ('max_age', 'Maximum Age'), ('min_income', 'Minimum Family Income'), ('max_income', 'Maximum Family Income'), ('min_percentage', 'Minimum Percentage'), ('exam_score', 'Exam Score Requirement'), ('state', 'State Requirement'), ('category', 'Category Requirement'), ('gender', 'Gender Requirement'), ('custom', 'Custom Rule')], db_index=True, max_length=50, verbose_name='Rule Type')),
                ('rule_value', models.JSONField(default=dict, help_text='Rule parameters (e.g., {"min": 18, "max": 25} for age)', verbose_name='Rule Value')),
                ('description', models.CharField(blank=True, help_text='Human-readable description of the rule', max_length=500, verbose_name='Description')),
                ('is_required', models.BooleanField(default=True, help_text='If False, this is an optional/preferred criterion', verbose_name='Is Required')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_eligibility_rules', to='scholarships.scholarship', verbose_name='Scholarship')),
            ],
            options={
                'verbose_name': 'Scholarship Eligibility Rule',
                'verbose_name_plural': 'Scholarship Eligibility Rules',
                'ordering': ['scholarship', 'order', 'rule_type'],
            },
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['student', '-created_at'], name='scholarship_student_1d5c07_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['scholarship', 'status'], name='scholarship_scholar_753ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='scholarship_status_4d3908_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipapplication',
            index=models.Index(fields=['student', 'scholarship'], name='scholarship_student_ad7b02_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarshipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'submitted', 'under_review'])), fields=('student', 'scholarship'), name='unique_scholarship_application'),
        ),
        migrations.AddIndex(
            model_name='applicationreview',
            index=models.Index(fields=['application', '-reviewed_at'], name='scholarship_applica_8442c2_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationreview',
            index=models.Index(fields=['reviewer', '-reviewed_at'], name='scholarship_reviewe_dff14e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationreview',
            index=models.Index(fields=['decision', '-reviewed_at'], name='scholarship_decisio_e1ae36_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipdocument',
            index=models.Index(fields=['application', 'document_type'], name='scholarship_applica_0f5996_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipeligibilityrule',
            index=models.Index(fields=['scholarship', 'is_required', 'order'], name='scholarship_scholar_04eaa2_idx'),
        ),
    ]
