# Generated by Django 6.0 on 2026-01-27 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('viewed', 'Viewed'), ('redirected', 'Redirected to Official Site'), ('applied', 'Applied (Self Reported)'), ('result_received', 'Result Received')], db_index=True, default='not_started', max_length=30)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_interacted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, help_text='Optional student notes', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='applicationreview',
            name='scholarship_applica_8442c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationreview',
            name='scholarship_reviewe_dff14e_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationreview',
            name='scholarship_decisio_e1ae36_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipapplication',
            name='scholarship_student_1d5c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipapplication',
            name='scholarship_scholar_753ddb_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipapplication',
            name='scholarship_status_4d3908_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipapplication',
            name='scholarship_student_ad7b02_idx',
        ),
        migrations.RemoveConstraint(
            model_name='scholarshipapplication',
            name='unique_scholarship_application',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipdocument',
            name='scholarship_applica_0f5996_idx',
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['application_deadline', 'title']},
        ),
        migrations.AlterModelOptions(
            name='scholarshipeligibilityrule',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='scholarship',
            name='scholarship_status_68222a_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarship',
            name='scholarship_provide_8ac917_idx',
        ),
        migrations.RemoveIndex(
            model_name='scholarshipeligibilityrule',
            name='scholarship_scholar_04eaa2_idx',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='official_url',
            field=models.URLField(blank=True, help_text='Official scholarship application page', null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount_description',
            field=models.CharField(blank=True, help_text='Example: Up to ₹50,000', max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='application_deadline',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Fast eligibility filtering'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(choices=[('merit_based', 'Merit Based'), ('need_based', 'Need Based'), ('sports', 'Sports'), ('minority', 'Minority'), ('disability', 'Disability'), ('research', 'Research'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='rule_type',
            field=models.CharField(choices=[('min_age', 'Minimum Age'), ('max_age', 'Maximum Age'), ('min_income', 'Minimum Family Income'), ('max_income', 'Maximum Family Income'), ('min_percentage', 'Minimum Percentage'), ('state', 'State'), ('category', 'Category'), ('gender', 'Gender'), ('custom', 'Custom Rule')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='rule_value',
            field=models.JSONField(help_text='Example: {"min": 18, "max": 25}'),
        ),
        migrations.AlterField(
            model_name='scholarshipeligibilityrule',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rule_list', to='scholarships.scholarship'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['status', 'application_deadline'], name='scholarship_status_3a431a_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['provider_name'], name='scholarship_provide_ac7a12_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipeligibilityrule',
            index=models.Index(fields=['rule_type'], name='scholarship_rule_ty_32eb77_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipeligibilityrule',
            index=models.Index(fields=['scholarship', 'rule_type'], name='scholarship_scholar_dfb148_idx'),
        ),
        migrations.AddField(
            model_name='scholarshipinteraction',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='scholarships.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarshipinteraction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='student',
        ),
        migrations.RemoveField(
            model_name='scholarshipdocument',
            name='application',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='application_instructions',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='provider_website',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='scholarshipeligibilityrule',
            name='is_required',
        ),
        migrations.AddIndex(
            model_name='scholarshipinteraction',
            index=models.Index(fields=['student', 'status'], name='scholarship_student_ead827_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarshipinteraction',
            index=models.Index(fields=['scholarship', 'status'], name='scholarship_scholar_718ce6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scholarshipinteraction',
            unique_together={('student', 'scholarship')},
        ),
        migrations.DeleteModel(
            name='ApplicationReview',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='ScholarshipDocument',
        ),
    ]
