# Generated by Django 6.0 on 2026-01-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarshipinteraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
