# Generated by Django 5.1.7 on 2026-01-27 06:16

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slugs for existing scholarships."""
    Scholarship = apps.get_model('scholarships', 'Scholarship')
    
    for scholarship in Scholarship.objects.filter(slug__isnull=True):
        if scholarship.title:
            base_slug = slugify(scholarship.title)
            slug = base_slug
            counter = 1
            
            # Ensure slug is unique
            while Scholarship.objects.filter(slug=slug).exclude(pk=scholarship.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            scholarship.slug = slug
            scholarship.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Reverse operation - set slugs to None."""
    Scholarship = apps.get_model('scholarships', 'Scholarship')
    Scholarship.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarship_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
