# Generated by Django 5.1.7 on 2026-01-27 06:20

from django.db import migrations, models
from django.utils.text import slugify


def ensure_all_slugs_populated(apps, schema_editor):
    """Ensure all scholarships have slugs before making field non-nullable."""
    Scholarship = apps.get_model('scholarships', 'Scholarship')
    
    for scholarship in Scholarship.objects.filter(slug__isnull=True):
        if scholarship.title:
            base_slug = slugify(scholarship.title)
            slug = base_slug
            counter = 1
            
            # Ensure slug is unique
            while Scholarship.objects.filter(slug=slug).exclude(pk=scholarship.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            scholarship.slug = slug
            scholarship.save(update_fields=['slug'])


def reverse_ensure_slugs(apps, schema_editor):
    """Reverse operation - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_populate_slugs'),
    ]

    operations = [
        migrations.RunPython(ensure_all_slugs_populated, reverse_ensure_slugs),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, db_index=True),
        ),
    ]
