# Generated by Django 5.1.7 on 2026-01-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0005_make_slug_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipinteraction',
            name='notification_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether follow-up notification has been sent'),
        ),
        migrations.AddField(
            model_name='scholarshipinteraction',
            name='redirected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was redirected to official website', null=True),
        ),
    ]
