# Generated by Django 5.1.7 on 2026-01-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0006_scholarshipinteraction_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Other', 'Other')], max_length=50, verbose_name='Stream')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State', 'State Board'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('Other', 'Other')], max_length=50, verbose_name='Board')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('Other', 'Other')], max_length=50, verbose_name='Category')),
                ('family_income_range', models.CharField(choices=[('₹0 – ₹1,00,000', '₹0 – ₹1,00,000'), ('₹1,00,000 – ₹2,50,000', '₹1,00,000 – ₹2,50,000'), ('₹2,50,000 – ₹5,00,000', '₹2,50,000 – ₹5,00,000'), ('₹5,00,000 – ₹10,00,000', '₹5,00,000 – ₹10,00,000'), ('₹10,00,000+', '₹10,00,000+')], max_length=50, verbose_name='Family Income Range')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=50, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_onboarding', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Scholarship Onboarding',
                'verbose_name_plural': 'Scholarship Onboardings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='scholarship_user_id_257992_idx'), models.Index(fields=['stream', 'state', 'category'], name='scholarship_stream_1bc5d1_idx')],
            },
        ),
    ]
