# Generated by Django 5.1.7 on 2026-01-12 10:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], db_index=True, max_length=20, unique=True, verbose_name='Difficulty Level')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
                'ordering': ['order', 'level'],
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Test Category',
                'verbose_name_plural': 'Test Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Test Title')),
                ('test_type', models.CharField(choices=[('full_length', 'Full Length'), ('practice', 'Practice'), ('sectional', 'Sectional'), ('topic_wise', 'Topic Wise')], db_index=True, max_length=30, verbose_name='Test Type')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Total Questions')),
                ('marks_per_question', models.FloatField(default=4.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks Per Question')),
                ('negative_marks', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative Marks Per Wrong Answer')),
                ('total_marks', models.FloatField(default=0.0, help_text='Auto-calculated: total_questions * marks_per_question', verbose_name='Total Marks')),
                ('duration_minutes', models.PositiveIntegerField(default=180, verbose_name='Duration (Minutes)')),
                ('is_vip', models.BooleanField(db_index=True, default=False, help_text='Requires premium subscription', verbose_name='VIP Test')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('instructions', models.TextField(blank=True, verbose_name='Test Instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('difficulty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='mocktest.difficultylevel', verbose_name='Difficulty Level')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_tests', to='mocktest.testcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Mock Test',
                'verbose_name_plural': 'Mock Tests',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(db_index=True, help_text='Position in the test', verbose_name='Question Number')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('integer', 'Integer Type'), ('numerical', 'Numerical Value')], db_index=True, default='mcq', max_length=30, verbose_name='Question Type')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('subject', models.CharField(db_index=True, max_length=50, verbose_name='Subject')),
                ('option_a', models.CharField(blank=True, max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(blank=True, max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='Option D')),
                ('correct_option', models.CharField(help_text='A, B, C, D, or numerical value', max_length=10, verbose_name='Correct Answer')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Topic')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('marks', models.FloatField(default=4.0, help_text='Marks for this question (can override test default)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks')),
                ('negative_marks', models.FloatField(default=1.0, help_text='Negative marks for wrong answer (can override test default)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative Marks')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('difficulty_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='mocktest.difficultylevel', verbose_name='Difficulty Level')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.mocktest', verbose_name='Mock Test')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['mock_test', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(choices=[('class_11', 'Class 11'), ('class_12', 'Class 12'), ('dropper', 'Dropper'), ('graduate', 'Graduate')], db_index=True, max_length=20, verbose_name='Class Level')),
                ('exam_target', models.CharField(choices=[('jee_main', 'JEE Main'), ('jee_advanced', 'JEE Advanced'), ('neet', 'NEET'), ('eapcet', 'EAPCET'), ('bitsat', 'BITSAT'), ('other', 'Other')], db_index=True, max_length=30, verbose_name='Exam Target')),
                ('total_xp', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Total XP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-total_xp', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('overall', 'Overall'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('exam_specific', 'Exam Specific')], db_index=True, default='overall', max_length=20, verbose_name='Leaderboard Type')),
                ('period_start', models.DateField(blank=True, db_index=True, help_text='Start date for period-based leaderboards', null=True, verbose_name='Period Start')),
                ('period_end', models.DateField(blank=True, db_index=True, help_text='End date for period-based leaderboards', null=True, verbose_name='Period End')),
                ('total_score', models.FloatField(db_index=True, default=0.0, verbose_name='Total Score')),
                ('total_tests', models.PositiveIntegerField(default=0, verbose_name='Total Tests Completed')),
                ('average_score', models.FloatField(default=0.0, verbose_name='Average Score')),
                ('rank', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Rank')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='mocktest.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard Entries',
                'ordering': ['leaderboard_type', 'rank', 'total_score'],
            },
        ),
        migrations.CreateModel(
            name='StudyGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Guild Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_guilds', to='mocktest.studentprofile', verbose_name='Guild Leader')),
                ('members', models.ManyToManyField(blank=True, related_name='guilds', to='mocktest.studentprofile', verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Study Guild',
                'verbose_name_plural': 'Study Guilds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True, default=0.0, verbose_name='Score')),
                ('percentage', models.FloatField(db_index=True, default=0.0, help_text='(score / total_marks) * 100', verbose_name='Percentage')),
                ('percentile', models.FloatField(db_index=True, default=0.0, verbose_name='Percentile')),
                ('correct_count', models.PositiveIntegerField(default=0, verbose_name='Correct Answers')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Wrong Answers')),
                ('unanswered_count', models.PositiveIntegerField(default=0, verbose_name='Unanswered Questions')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Completed At')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Is Completed')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Taken (Seconds)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to='mocktest.mocktest', verbose_name='Mock Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='mocktest.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Test Attempt',
                'verbose_name_plural': 'Test Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, help_text='A, B, C, D, or numerical value', max_length=50, verbose_name='Selected Answer')),
                ('is_correct', models.BooleanField(db_index=True, default=False, verbose_name='Is Correct')),
                ('marks_obtained', models.FloatField(default=0.0, help_text='Positive for correct, negative for wrong, 0 for unanswered', verbose_name='Marks Obtained')),
                ('time_taken_seconds', models.PositiveIntegerField(default=0, verbose_name='Time Taken (Seconds)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='mocktest.question', verbose_name='Question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mocktest.testattempt', verbose_name='Test Attempt')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'ordering': ['attempt', 'question__question_number'],
            },
        ),
        migrations.CreateModel(
            name='MistakeNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(blank=True, choices=[('conceptual', 'Conceptual Error'), ('calculation', 'Calculation Error'), ('silly', 'Silly Mistake'), ('time_pressure', 'Time Pressure'), ('not_attempted', 'Not Attempted')], db_index=True, max_length=30, verbose_name='Error Type')),
                ('notes', models.TextField(blank=True, help_text='Student notes about the mistake', verbose_name='Notes')),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Logged At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mocktest.question', verbose_name='Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mocktest.studentprofile', verbose_name='Student')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mocktest.testattempt', verbose_name='Test Attempt')),
            ],
            options={
                'verbose_name': 'Mistake Notebook Entry',
                'verbose_name_plural': 'Mistake Notebook Entries',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, help_text='Description of the action that earned XP', max_length=200, verbose_name='Action')),
                ('xp_amount', models.PositiveIntegerField(db_index=True, verbose_name='XP Amount')),
                ('source_type', models.CharField(blank=True, db_index=True, help_text='Type of source (test_completed, referral, etc.)', max_length=50, verbose_name='Source Type')),
                ('source_id', models.BigIntegerField(blank=True, db_index=True, help_text='ID of the source object', null=True, verbose_name='Source ID')),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Logged At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to='mocktest.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'XP Log',
                'verbose_name_plural': 'XP Logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Created At')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Is Used')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Phone OTP',
                'verbose_name_plural': 'Phone OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used', '-created_at'], name='mocktest_ph_user_id_bb152e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['mock_test', 'question_number'], name='mocktest_qu_mock_te_b1ae65_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty_level'], name='mocktest_qu_subject_01806e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'subject'], name='mocktest_qu_topic_8a1a5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('mock_test', 'question_number'), name='unique_question_number_per_test'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', 'rank'], name='mocktest_le_leaderb_72f886_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['leaderboard_type', '-total_score'], name='mocktest_le_leaderb_84cb95_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['student', 'leaderboard_type'], name='mocktest_le_student_506085_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.UniqueConstraint(fields=('student', 'leaderboard_type', 'period_start', 'period_end'), name='unique_leaderboard_entry'),
        ),
        migrations.AddIndex(
            model_name='studyguild',
            index=models.Index(fields=['leader', 'is_active'], name='mocktest_st_leader__648fca_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', '-started_at'], name='mocktest_te_student_88fab5_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['mock_test', '-score'], name='mocktest_te_mock_te_9ff006_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['is_completed', '-completed_at'], name='mocktest_te_is_comp_9a5ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'mock_test', 'is_completed'], name='mocktest_te_student_b52a3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', True)), fields=('student', 'mock_test'), name='unique_test_attempt_per_student'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='mocktest_st_attempt_1d629b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='mocktest_st_attempt_e9eecc_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
        migrations.AddIndex(
            model_name='mistakenotebook',
            index=models.Index(fields=['student', '-logged_at'], name='mocktest_mi_student_bf22e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakenotebook',
            index=models.Index(fields=['student', 'error_type'], name='mocktest_mi_student_1dae5b_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakenotebook',
            index=models.Index(fields=['question', 'student'], name='mocktest_mi_questio_53b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['category', 'test_type', 'is_active'], name='mocktest_mo_categor_5c63d7_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['is_vip', 'is_active'], name='mocktest_mo_is_vip_206029_idx'),
        ),
        migrations.AddIndex(
            model_name='xplog',
            index=models.Index(fields=['student', '-logged_at'], name='mocktest_xp_student_ef059f_idx'),
        ),
        migrations.AddIndex(
            model_name='xplog',
            index=models.Index(fields=['student', 'source_type'], name='mocktest_xp_student_89fd20_idx'),
        ),
    ]
