# Generated by Django 5.1.7 on 2026-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.CharField(blank=True, db_index=True, help_text='Exam name (e.g., JEE Main, NEET, AP EAPCET)', max_length=50, null=True, verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Year of the question (e.g., 2021, 2022, 2023)', null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='generation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration used to generate custom tests (exam, years, subjects, etc.)', verbose_name='Generation Config'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test_mode',
            field=models.CharField(choices=[('preset', 'Preset'), ('custom', 'Custom')], db_index=True, default='preset', help_text='Whether this is a preset test or custom generated test', max_length=20, verbose_name='Test Mode'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'year'], name='mocktest_qu_exam_b0186e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam', 'year', 'subject'], name='mocktest_qu_exam_8b38ce_idx'),
        ),
    ]
