# Generated by Django 5.1.7 on 2026-01-14 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_question_exam_question_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique code for the exam (e.g., jee_main, neet)', max_length=50, unique=True, verbose_name='Exam Code')),
                ('name', models.CharField(db_index=True, help_text='Display name (e.g., JEE Main, NEET)', max_length=100, verbose_name='Exam Name')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='mocktest_qu_exam_id_7fce8d_idx',
            old_name='mocktest_qu_exam_b0186e_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='mocktest_qu_exam_id_a6d694_idx',
            old_name='mocktest_qu_exam_8b38ce_idx',
        ),
        migrations.AddField(
            model_name='mocktest',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Exam this test belongs to (recommended)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mock_tests', to='mocktest.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Exam this question belongs to (required for new questions)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='mocktest.exam', verbose_name='Exam'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['exam', 'test_type', 'is_active'], name='mocktest_mo_exam_id_530303_idx'),
        ),
    ]
