# Generated by Django 5.1.7 on 2026-01-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0003_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='mock_test',
            field=models.ForeignKey(blank=True, help_text='Mock test this question belongs to (null for standalone questions in question bank)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.mocktest', verbose_name='Mock Test'),
        ),
    ]
