# Generated by Django 5.1.7 on 2026-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_update_questions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocktest',
            name='test_type',
            field=models.CharField(choices=[('full_length', 'Full Length'), ('practice', 'Practice'), ('sectional', 'Sectional'), ('custom', 'Custom'), ('topic_wise', 'Topic Wise')], db_index=True, max_length=30, verbose_name='Test Type'),
        ),
    ]
