# Generated by Django 5.1.7 on 2026-01-14 10:46

import django.db.models.deletion
from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists (SQLite specific)
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX IF EXISTS mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - index recreation not needed as we're removing the field."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0006_alter_mocktest_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='category',
        ),
        migrations.RunPython(
            remove_index_if_exists,
            reverse_remove_index,
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Exam this test belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mock_tests', to='mocktest.exam', verbose_name='Exam'),
        ),
        migrations.DeleteModel(
            name='TestCategory',
        ),
    ]
