# Generated by Django 5.1.7 on 2026-01-14 10:46

from django.db import migrations


def update_questions_exam(apps, schema_editor):
    """Update all Question records to have exam_id = 1."""
    Question = apps.get_model('mocktest', 'Question')
    Exam = apps.get_model('mocktest', 'Exam')
    
    # Check if Exam with id=1 exists, if not create it
    exam, created = Exam.objects.get_or_create(
        id=1,
        defaults={
            'code': 'DEFAULT',
            'name': 'Default Exam',
            'is_active': True
        }
    )
    
    # Update all questions to have exam_id = 1
    Question.objects.all().update(exam_id=1)
    
    print(f"Updated {Question.objects.count()} questions to exam_id = 1")


def reverse_update_questions_exam(apps, schema_editor):
    """Reverse operation - set exam to None (not recommended but needed for migration reversibility)."""
    Question = apps.get_model('mocktest', 'Question')
    Question.objects.all().update(exam=None)
    print("Reverted all questions to have exam = None")


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0007_remove_mocktest_category_and_more'),
    ]

    operations = [
        migrations.RunPython(
            update_questions_exam,
            reverse_update_questions_exam,
        ),
    ]
