# Generated by Django 5.1.7 on 2026-01-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0008_update_questions_exam'),
    ]

    operations = [
        # migrations.RemoveIndex(
        #     model_name='mocktest',
        #     name='mocktest_mo_categor_5c63d7_idx',
        # ),
        migrations.AddField(
            model_name='studentprofile',
            name='onboarding_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether user has completed the onboarding process', verbose_name='Onboarding Completed'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_rank',
            field=models.PositiveIntegerField(blank=True, help_text="User's target rank/score goal", null=True, verbose_name='Target Rank'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tests_per_week',
            field=models.CharField(blank=True, help_text='User\'s preferred test frequency (e.g., "1-2 tests", "3-5 tests", "Daily practice")', max_length=50, null=True, verbose_name='Tests Per Week'),
        ),
    ]
