# Generated by Django 5.1.7 on 2026-01-16 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0009_remove_mocktest_mocktest_mo_categor_5c63d7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this focus record', verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('partial', 'Partial')], db_index=True, default='present', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('mock_test', 'Mock Test'), ('custom_test', 'Custom Test'), ('mistake_review', 'Mistake Review')], db_index=True, help_text='What activity marked this day as present', max_length=30, verbose_name='Source')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Daily Focus',
                'verbose_name_plural': 'Daily Focus Records',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dailyfocus',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_focus_records', to='mocktest.studentprofile', verbose_name='Student'),
        ),
        migrations.AddIndex(
            model_name='dailyfocus',
            index=models.Index(fields=['student', '-date'], name='mocktest_da_student_5ece35_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyfocus',
            index=models.Index(fields=['student', 'date'], name='mocktest_da_student_8287d6_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyfocus',
            index=models.Index(fields=['date', 'status'], name='mocktest_da_date_244828_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyfocus',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_daily_focus_per_student'),
        ),
    ]
