# Generated by Django 5.1.7 on 2026-01-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def safe_remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    with connection.cursor() as cursor:
        # Check if index exists in SQLite
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX IF EXISTS mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - do nothing since index shouldn't exist."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0010_dailyfocus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_index_if_exists,
            reverse_remove_index,
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('start_time', models.DateTimeField()),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('password_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('participant_limit', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left'), ('kicked', 'Kicked')], default='joined', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mocktest.exam'),
        ),
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mocktest.room'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
