# Generated by Django 5.1.7 on 2026-01-19 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def safe_remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    with connection.cursor() as cursor:
        # Check if index exists in SQLite
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX IF EXISTS mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - do nothing since index shouldn't exist."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0011_room_roomparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_index_if_exists,
            reverse_remove_index,
        ),
        migrations.CreateModel(
            name='ParticipantAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, help_text='Selected answer option (A, B, C, D, etc.)', max_length=10, null=True, verbose_name='Selected Option')),
                ('answer_text', models.TextField(blank=True, help_text='Text answer for non-MCQ questions', null=True, verbose_name='Answer Text')),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether the answer is correct (calculated after submission)', null=True, verbose_name='Is Correct')),
                ('marks_obtained', models.FloatField(default=0.0, help_text='Marks obtained for this question', verbose_name='Marks Obtained')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, help_text='Time spent on this question in seconds', verbose_name='Time Spent (seconds)')),
                ('started_at', models.DateTimeField(blank=True, help_text='When participant started answering this question', null=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When participant submitted answer', null=True, verbose_name='Submitted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Participant Attempt',
                'verbose_name_plural': 'Participant Attempts',
                'ordering': ['room_question__question_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(help_text='Order of question in the room test', verbose_name='Question Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Room Question',
                'verbose_name_plural': 'Room Questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['joined_at'], 'verbose_name': 'Room Participant', 'verbose_name_plural': 'Room Participants'},
        ),
        migrations.AddField(
            model_name='room',
            name='allow_pause',
            field=models.BooleanField(default=False, help_text='Allow participants to pause the test', verbose_name='Allow Pause'),
        ),
        migrations.AddField(
            model_name='room',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed')], default='mixed', max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_questions',
            field=models.PositiveIntegerField(default=10, verbose_name='Number of Questions'),
        ),
        migrations.AddField(
            model_name='room',
            name='question_type_mix',
            field=models.CharField(choices=[('mcq', 'MCQ Only'), ('true_false', 'True/False Only'), ('fill_blank', 'Fill in the Blank Only'), ('mixed', 'Mixed')], default='mixed', max_length=20, verbose_name='Question Type Mix'),
        ),
        migrations.AddField(
            model_name='room',
            name='question_types',
            field=models.JSONField(blank=True, default=list, help_text='List of question types to include (MCQ, INTEGER, NUMERICAL, etc.)', null=True, verbose_name='Question Types'),
        ),
        migrations.AddField(
            model_name='room',
            name='randomization_mode',
            field=models.CharField(choices=[('none', 'No Randomization'), ('question_order', 'Randomize Question Order'), ('question_and_options', 'Randomize Questions & Options')], default='question_order', max_length=30, verbose_name='Randomization Mode'),
        ),
        migrations.AddField(
            model_name='room',
            name='subject_mode',
            field=models.CharField(choices=[('specific', 'Specific Subjects'), ('random', 'Random')], default='random', max_length=20, verbose_name='Subject Selection Mode'),
        ),
        migrations.AddField(
            model_name='room',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text="List of subjects/topics (used when subject_mode='specific')", null=True, verbose_name='Selected Subjects'),
        ),
        migrations.AddField(
            model_name='room',
            name='time_buffer',
            field=models.PositiveIntegerField(default=2, help_text='Additional time buffer in minutes (1-2 minutes recommended)', verbose_name='Time Buffer (minutes)'),
        ),
        migrations.AddField(
            model_name='room',
            name='time_per_question',
            field=models.FloatField(default=2.0, help_text='Time per question in minutes (supports decimals like 1.5)', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Time Per Question (minutes)'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='randomization_seed',
            field=models.IntegerField(blank=True, help_text='Random seed for question/option randomization per participant', null=True, verbose_name='Randomization Seed'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Room Code'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.PositiveIntegerField(default=20, help_text='Total duration in minutes (auto-calculated: number_of_questions × time_per_question)', verbose_name='Total Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mocktest.exam', verbose_name='Exam'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='room',
            name='participant_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited', verbose_name='Participant Limit'),
        ),
        migrations.AlterField(
            model_name='room',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password Hash'),
        ),
        migrations.AlterField(
            model_name='room',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10, verbose_name='Privacy'),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('completed', 'Completed'), ('locked', 'Locked')], db_index=True, default='waiting', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='topics',
            field=models.JSONField(blank=True, null=True, verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Joined At'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='mocktest.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='status',
            field=models.CharField(choices=[('joined', 'Joined'), ('left', 'Left'), ('kicked', 'Kicked')], db_index=True, default='joined', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='roomparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['code'], name='mocktest_ro_code_7faf72_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'start_time'], name='mocktest_ro_status_396c22_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host', 'status'], name='mocktest_ro_host_id_4e8ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['room', 'status'], name='mocktest_ro_room_id_f9ffe3_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['user', 'status'], name='mocktest_ro_user_id_7fb74d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'joined')), fields=('room', 'user'), name='unique_active_participant_per_room'),
        ),
        migrations.AddField(
            model_name='participantattempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktest.roomparticipant', verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='roomquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='mocktest.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='roomquestion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='mocktest.room', verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='participantattempt',
            name='room_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mocktest.roomquestion', verbose_name='Room Question'),
        ),
        migrations.AddIndex(
            model_name='roomquestion',
            index=models.Index(fields=['room', 'question_number'], name='mocktest_ro_room_id_74adaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomquestion',
            unique_together={('room', 'question_number')},
        ),
        migrations.AddIndex(
            model_name='participantattempt',
            index=models.Index(fields=['participant', 'room_question'], name='mocktest_pa_partici_c84ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='participantattempt',
            index=models.Index(fields=['participant', 'is_correct'], name='mocktest_pa_partici_e7d996_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participantattempt',
            unique_together={('participant', 'room_question')},
        ),
    ]
