# Generated by Django 5.1.7 on 2026-01-19 11:12

from django.db import migrations, models, connection


def safe_remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    with connection.cursor() as cursor:
        # Check if index exists in SQLite
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX IF EXISTS mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - do nothing since index shouldn't exist."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0012_participantattempt_roomquestion_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_index_if_exists,
            reverse_remove_index,
        ),
        migrations.AlterField(
            model_name='room',
            name='question_type_mix',
            field=models.CharField(choices=[('mcq', 'MCQ Only'), ('integer', 'Integer Type Only'), ('numerical', 'Numerical Type Only'), ('mixed', 'Mixed')], default='mixed', max_length=20, verbose_name='Question Type Mix'),
        ),
    ]
