# Generated by Django 5.1.7 on 2026-01-20 05:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0013_remove_mocktest_mocktest_mo_categor_5c63d7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(db_index=True, help_text='Position of this question in the test', verbose_name='Question Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Mock Test Question',
                'verbose_name_plural': 'Mock Test Questions',
                'ordering': ['mock_test', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('integer', 'Integer Type'), ('numerical', 'Numerical Value')], db_index=True, default='mcq', max_length=30, verbose_name='Question Type')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('subject', models.CharField(db_index=True, max_length=50, verbose_name='Subject')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, help_text='Year of the question (e.g., 2021, 2022, 2023)', null=True, verbose_name='Year')),
                ('option_a', models.CharField(blank=True, max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(blank=True, max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='Option D')),
                ('correct_option', models.CharField(help_text='A, B, C, D, or numerical value', max_length=10, verbose_name='Correct Answer')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Topic')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('marks', models.FloatField(default=4.0, help_text='Marks for this question', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Marks')),
                ('negative_marks', models.FloatField(default=1.0, help_text='Negative marks for wrong answer', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negative Marks')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - set to False to hide question without deleting', verbose_name='Is Active')),
                ('question_hash', models.CharField(db_index=True, help_text='SHA256 hash of (text + exam_id + year + subject) for duplicate detection', max_length=64, unique=True, verbose_name='Question Hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Question Bank',
                'verbose_name_plural': 'Question Bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['attempt'], 'verbose_name': 'Student Answer', 'verbose_name_plural': 'Student Answers'},
        ),
        migrations.RemoveConstraint(
            model_name='studentanswer',
            name='unique_answer_per_question',
        ),
        # Note: mocktest_mo_categor_5c63d7_idx was already removed in migration 0013
        # migrations.RemoveIndex(
        #     model_name='mocktest',
        #     name='mocktest_mo_categor_5c63d7_idx',
        # ),
        migrations.AddField(
            model_name='question',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=True, help_text='True for legacy questions. New questions should use QuestionBank.', verbose_name='Deprecated'),
        ),
        migrations.AlterField(
            model_name='mistakenotebook',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Legacy question reference. Use question_bank for new records.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mocktest.question', verbose_name='Question (Legacy)'),
        ),
        migrations.AlterField(
            model_name='roomquestion',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Legacy question reference. Use question_bank for new records.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='mocktest.question', verbose_name='Question (Legacy)'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(blank=True, help_text='Legacy question reference. Use question_bank for new records.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='mocktest.question', verbose_name='Question (Legacy)'),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='mock_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='mocktest.mocktest', verbose_name='Mock Test'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='difficulty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_questions', to='mocktest.difficultylevel', verbose_name='Difficulty Level'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Exam this question belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_questions', to='mocktest.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='mocktestquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_assignments', to='mocktest.questionbank', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='mistakenotebook',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Reference to QuestionBank (preferred for new records)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='mocktest.questionbank', verbose_name='Question Bank'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Link to QuestionBank if this question has been migrated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_questions', to='mocktest.questionbank', verbose_name='Question Bank Reference'),
        ),
        migrations.AddField(
            model_name='roomquestion',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Reference to QuestionBank (preferred for new records)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='mocktest.questionbank', verbose_name='Question Bank'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question_bank',
            field=models.ForeignKey(blank=True, help_text='Reference to QuestionBank (preferred for new records)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='mocktest.questionbank', verbose_name='Question Bank'),
        ),
        migrations.AddIndex(
            model_name='mistakenotebook',
            index=models.Index(fields=['question_bank', 'student'], name='mocktest_mi_questio_2654d7_idx'),
        ),
        migrations.AddIndex(
            model_name='roomquestion',
            index=models.Index(fields=['room', 'question'], name='mocktest_ro_room_id_3a0f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='roomquestion',
            index=models.Index(fields=['room', 'question_bank'], name='mocktest_ro_room_id_c7f448_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question_bank'], name='mocktest_st_attempt_da2b0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='mistakenotebook',
            constraint=models.CheckConstraint(condition=models.Q(('question__isnull', False), ('question_bank__isnull', False), _connector='OR'), name='mistake_has_question_reference'),
        ),
        migrations.AddConstraint(
            model_name='roomquestion',
            constraint=models.CheckConstraint(condition=models.Q(('question__isnull', False), ('question_bank__isnull', False), _connector='OR'), name='room_question_has_question_reference'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.CheckConstraint(condition=models.Q(('question__isnull', False), ('question_bank__isnull', False), _connector='OR'), name='student_answer_has_question_reference'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question_bank__isnull', False)), fields=('attempt', 'question_bank'), name='unique_answer_per_question_bank'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['exam', 'year'], name='mocktest_qu_exam_id_fd926e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['subject', 'difficulty_level'], name='mocktest_qu_subject_71bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['topic', 'subject'], name='mocktest_qu_topic_8bede3_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['exam', 'year', 'subject'], name='mocktest_qu_exam_id_de007e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_active', 'exam'], name='mocktest_qu_is_acti_885d9e_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('question_hash',), name='unique_question_hash'),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['mock_test', 'question_number'], name='mocktest_mo_mock_te_afe4a8_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestquestion',
            index=models.Index(fields=['mock_test', 'question'], name='mocktest_mo_mock_te_28632e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocktestquestion',
            constraint=models.UniqueConstraint(fields=('mock_test', 'question_number'), name='unique_mocktestquestion_number_per_test'),
        ),
        migrations.AddConstraint(
            model_name='mocktestquestion',
            constraint=models.UniqueConstraint(fields=('mock_test', 'question'), name='unique_question_per_mocktest'),
        ),
    ]
