# Generated by Django 5.1.7 on 2026-01-20 06:00

from django.db import migrations


def ensure_all_records_have_question_bank(apps, schema_editor):
    """
    Ensure all StudentAnswer, MistakeNotebook, and RoomQuestion records have question_bank.
    
    This migration ensures that any remaining records that might have question but not question_bank
    are migrated before we make question_bank required.
    """
    StudentAnswer = apps.get_model('mocktest', 'StudentAnswer')
    MistakeNotebook = apps.get_model('mocktest', 'MistakeNotebook')
    RoomQuestion = apps.get_model('mocktest', 'RoomQuestion')
    Question = apps.get_model('mocktest', 'Question')
    QuestionBank = apps.get_model('mocktest', 'QuestionBank')
    
    # Migrate StudentAnswer records
    student_answers_without_bank = StudentAnswer.objects.filter(question_bank__isnull=True, question__isnull=False)
    migrated_count = 0
    skipped_count = 0
    
    for answer in student_answers_without_bank:
        if answer.question and answer.question.question_bank:
            # Check if a record with same attempt and question_bank already exists
            existing = StudentAnswer.objects.filter(
                attempt=answer.attempt,
                question_bank=answer.question.question_bank
            ).exclude(id=answer.id).first()
            
            if existing:
                # Merge: update existing record with this one's data if needed
                # Then delete the duplicate
                answer.delete()
                skipped_count += 1
            else:
                answer.question_bank = answer.question.question_bank
                answer.save(update_fields=['question_bank_id'])
                migrated_count += 1
    
    print(f"Migrated {migrated_count} StudentAnswer records, skipped {skipped_count} duplicates")
    
    # Migrate MistakeNotebook records
    mistakes_without_bank = MistakeNotebook.objects.filter(question_bank__isnull=True, question__isnull=False)
    migrated_count = 0
    
    for mistake in mistakes_without_bank:
        if mistake.question and mistake.question.question_bank:
            mistake.question_bank = mistake.question.question_bank
            mistake.save(update_fields=['question_bank_id'])
            migrated_count += 1
    
    print(f"Migrated {migrated_count} MistakeNotebook records")
    
    # Migrate RoomQuestion records
    room_questions_without_bank = RoomQuestion.objects.filter(question_bank__isnull=True, question__isnull=False)
    migrated_count = 0
    
    for rq in room_questions_without_bank:
        if rq.question and rq.question.question_bank:
            rq.question_bank = rq.question.question_bank
            rq.save(update_fields=['question_bank_id'])
            migrated_count += 1
    
    print(f"Migrated {migrated_count} RoomQuestion records")
    
    # Check for any records still without question_bank
    remaining = (
        StudentAnswer.objects.filter(question_bank__isnull=True).count() +
        MistakeNotebook.objects.filter(question_bank__isnull=True).count() +
        RoomQuestion.objects.filter(question_bank__isnull=True).count()
    )
    
    if remaining > 0:
        print(f"WARNING: {remaining} records still without question_bank. These will need manual handling.")


def reverse_migration(apps, schema_editor):
    """Reverse migration - no-op since we're just ensuring data consistency."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0015_migrate_questions_to_bank'),
    ]

    operations = [
        migrations.RunPython(
            ensure_all_records_have_question_bank,
            reverse_code=reverse_migration
        ),
    ]
