# Generated by Django 5.1.7 on 2026-01-20 06:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_remaining_question_references(apps, schema_editor):
    """
    Final migration step: Ensure all records use question_bank before removing question FK.
    Any records still using question FK will be migrated to question_bank.
    """
    StudentAnswer = apps.get_model('mocktest', 'StudentAnswer')
    MistakeNotebook = apps.get_model('mocktest', 'MistakeNotebook')
    RoomQuestion = apps.get_model('mocktest', 'RoomQuestion')
    Question = apps.get_model('mocktest', 'Question')
    
    # Migrate any remaining StudentAnswer records
    migrated = 0
    for answer in StudentAnswer.objects.filter(question_bank__isnull=True, question__isnull=False):
        if answer.question and answer.question.question_bank:
            answer.question_bank = answer.question.question_bank
            answer.save(update_fields=['question_bank_id'])
            migrated += 1
    print(f"Migrated {migrated} StudentAnswer records")
    
    # Migrate any remaining MistakeNotebook records
    migrated = 0
    for mistake in MistakeNotebook.objects.filter(question_bank__isnull=True, question__isnull=False):
        if mistake.question and mistake.question.question_bank:
            mistake.question_bank = mistake.question.question_bank
            mistake.save(update_fields=['question_bank_id'])
            migrated += 1
    print(f"Migrated {migrated} MistakeNotebook records")
    
    # Migrate any remaining RoomQuestion records
    migrated = 0
    for rq in RoomQuestion.objects.filter(question_bank__isnull=True, question__isnull=False):
        if rq.question and rq.question.question_bank:
            rq.question_bank = rq.question.question_bank
            rq.save(update_fields=['question_bank_id'])
            migrated += 1
    print(f"Migrated {migrated} RoomQuestion records")


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0016_ensure_question_bank_populated'),
    ]

    operations = [
        # Step 1: Migrate any remaining question references
        migrations.RunPython(
            migrate_remaining_question_references,
            reverse_code=migrations.RunPython.noop
        ),
        # Step 2: Remove indexes that reference question field (MUST be before removing fields)
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='mocktest_st_attempt_1d629b_idx',
        ),
        migrations.RemoveIndex(
            model_name='mistakenotebook',
            name='mocktest_mi_questio_53b1c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='roomquestion',
            name='mocktest_ro_room_id_3a0f5c_idx',
        ),
        # Step 3: Remove constraints that referenced question (MUST be before removing fields)
        migrations.RemoveConstraint(
            model_name='studentanswer',
            name='student_answer_has_question_reference',
        ),
        migrations.RemoveConstraint(
            model_name='studentanswer',
            name='unique_answer_per_question',
        ),
        migrations.RemoveConstraint(
            model_name='mistakenotebook',
            name='mistake_has_question_reference',
        ),
        migrations.RemoveConstraint(
            model_name='roomquestion',
            name='room_question_has_question_reference',
        ),
        # Step 4: Remove question FK fields
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mistakenotebook',
            name='question',
        ),
        migrations.RemoveField(
            model_name='roomquestion',
            name='question',
        ),
        # Step 5: Make question_bank required (remove null=True, blank=True)
        # Note: We do this after removing question field to avoid index conflicts
        migrations.AlterField(
            model_name='studentanswer',
            name='question_bank',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='student_answers',
                to='mocktest.questionbank',
                verbose_name='Question Bank'
            ),
        ),
        migrations.AlterField(
            model_name='mistakenotebook',
            name='question_bank',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='mistakes',
                to='mocktest.questionbank',
                verbose_name='Question Bank'
            ),
        ),
        migrations.AlterField(
            model_name='roomquestion',
            name='question_bank',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='room_questions',
                to='mocktest.questionbank',
                verbose_name='Question Bank'
            ),
        ),
        # Step 6: Delete Question model
        migrations.DeleteModel(
            name='Question',
        ),
    ]
