# Generated by Django 6.0 on 2026-01-21 06:07

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists in SQLite
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - index recreation would need original definition."""
    # Index removal is not reversible without original definition
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0017_remove_question_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentanswer',
            name='unique_answer_per_question_bank',
        ),
        migrations.RunPython(
            remove_index_if_exists,
            reverse_remove_index,
        ),
        migrations.AddField(
            model_name='exam',
            name='logo',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Exam Logo'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question_bank'), name='unique_answer_per_question_bank'),
        ),
    ]
