# Generated by Django 5.1.7 on 2026-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0018_remove_studentanswer_unique_answer_per_question_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attempt_mode',
            field=models.CharField(choices=[('ALL_AT_ONCE', 'All at once'), ('INDIVIDUAL', 'Individual')], default='ALL_AT_ONCE', max_length=20, verbose_name='Attempt Mode'),
        ),
    ]
