# Generated by Django 5.1.7 on 2026-01-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0019_add_attempt_mode_to_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='participant_start_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this participant started the test (for INDIVIDUAL mode)', null=True, verbose_name='Participant Start Time'),
        ),
    ]
