# Generated by Django 5.1.7 on 2026-01-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0020_add_participant_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='time_buffer',
        ),
    ]
