# Generated by Django 6.0 on 2026-01-27 06:08

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Remove the index if it exists (handles case where it was already removed)."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists (SQLite syntax)
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX mocktest_mo_categor_5c63d7_idx")


def reverse_operation(apps, schema_editor):
    """Reverse operation - index recreation not needed as it was obsolete."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0022_remove_mocktest_mocktest_mo_categor_5c63d7_idx'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_operation,
        ),
    ]
