# Generated by Django 6.0 on 2026-01-27 10:21

from django.db import migrations


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index only if it exists."""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT name FROM sqlite_master
            WHERE type='index' AND name='mocktest_mo_categor_5c63d7_idx'
        """)
        if cursor.fetchone():
            cursor.execute("DROP INDEX mocktest_mo_categor_5c63d7_idx")


def reverse_remove_index(apps, schema_editor):
    """Reverse operation - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0023_remove_mocktest_mocktest_mo_categor_5c63d7_idx'),
    ]

    operations = [
        migrations.RunPython(remove_index_if_exists, reverse_remove_index),
    ]
