# Generated by Django 6.0 on 2025-12-31 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Type', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government')], default='Private', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('degree', models.CharField(choices=[('Bachelor of Technology', 'B.Tech'), ('Master of Technology', 'M.Tech'), ('Bachelor of Science', 'B.Sc'), ('Master of Science', 'M.Sc'), ('Bachelor of Arts', 'B.A'), ('Master of Arts', 'M.A')], default='B.Tech', max_length=50)),
                ('branch', models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronics Engineering', 'EEE'), ('Mechanical Engineering', 'ME'), ('Civil Engineering', 'CE')], default='CSE', max_length=100)),
                ('total_seats', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.collegemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CutoffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('Category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=10)),
                ('quota', models.CharField(choices=[('State', 'State'), ('AIQ', 'AIQ')], max_length=10)),
                ('opening_rank', models.IntegerField()),
                ('closing_rank', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.coursemodel')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.exammodel')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_rank', models.IntegerField()),
                ('category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=10)),
                ('State', models.CharField(max_length=255)),
                ('branch_list', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_result', models.JSONField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.exammodel')),
            ],
        ),
    ]
