# Generated by Django 5.1.7 on 2026-01-12 10:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='College Name')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='College Code')),
                ('location', models.CharField(db_index=True, max_length=255, verbose_name='Location')),
                ('state', models.CharField(db_index=True, max_length=100, verbose_name='State')),
                ('college_type', models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('autonomous', 'Autonomous'), ('deemed', 'Deemed University')], db_index=True, default='private', max_length=20, verbose_name='College Type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['state', 'college_type'], name='predictor_c_state_b6f32a_idx'), models.Index(fields=['is_active', 'name'], name='predictor_c_is_acti_eca558_idx')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Course Name')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Duration (Years)')),
                ('degree', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bsc', 'B.Sc'), ('msc', 'M.Sc'), ('ba', 'B.A'), ('ma', 'M.A'), ('mba', 'MBA'), ('phd', 'Ph.D')], db_index=True, default='btech', max_length=50, verbose_name='Degree Type')),
                ('branch', models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('ece', 'Electronics and Communication Engineering'), ('eee', 'Electrical and Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('it', 'Information Technology'), ('ae', 'Aerospace Engineering'), ('che', 'Chemical Engineering'), ('other', 'Other')], db_index=True, default='cse', max_length=100, verbose_name='Branch')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Total Seats')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='predictor.college', verbose_name='College')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['college', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Exam Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the exam (e.g., JEE_MAIN, NEET)', max_length=50, unique=True, verbose_name='Exam Code')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='predictor_e_is_acti_b8ba27_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('category', models.CharField(choices=[('general', 'General'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC'), ('obc_ncl', 'OBC-NCL'), ('ews', 'EWS'), ('gen_ews', 'GEN-EWS'), ('gen_ews_pwd', 'GEN-EWS-PWD'), ('gen_pwd', 'GEN-PWD'), ('obc_ncl_pwd', 'OBC-NCL-PWD'), ('sc_pwd', 'SC-PWD'), ('st_pwd', 'ST-PWD'), ('ews_pwd', 'EWS-PWD')], db_index=True, max_length=20, verbose_name='Category')),
                ('quota', models.CharField(choices=[('state', 'State'), ('aiq', 'All India Quota'), ('ai', 'All India'), ('ap', 'Andhra Pradesh'), ('go', 'Goa'), ('hs', 'Home State'), ('jk', 'Jammu & Kashmir'), ('la', 'Ladakh'), ('os', 'Other State')], db_index=True, max_length=10, verbose_name='Quota')),
                ('seat_type', models.CharField(choices=[('open', 'OPEN'), ('open_pwd', 'OPEN (PwD)'), ('obc_ncl', 'OBC-NCL'), ('obc_ncl_pwd', 'OBC-NCL (PwD)'), ('sc', 'SC'), ('sc_pwd', 'SC (PwD)'), ('st', 'ST'), ('st_pwd', 'ST (PwD)'), ('ews', 'EWS'), ('ews_pwd', 'EWS (PwD)')], db_index=True, default='open', max_length=20, verbose_name='Seat Type')),
                ('state', models.CharField(db_index=True, default='All', max_length=255, verbose_name='State')),
                ('opening_rank', models.PositiveIntegerField(db_index=True, verbose_name='Opening Rank')),
                ('closing_rank', models.PositiveIntegerField(db_index=True, verbose_name='Closing Rank')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='predictor.course', verbose_name='Course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='predictor.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Cutoff',
                'verbose_name_plural': 'Cutoffs',
                'ordering': ['-year', 'exam', 'opening_rank'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_rank', models.PositiveIntegerField(db_index=True, verbose_name='Input Rank')),
                ('category', models.CharField(choices=[('general', 'General'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC')], db_index=True, max_length=10, verbose_name='Category')),
                ('state', models.CharField(db_index=True, max_length=255, verbose_name='State')),
                ('branch_list', models.JSONField(blank=True, default=list, help_text='List of preferred branch codes', verbose_name='Preferred Branches')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, help_text='Complete input data at time of prediction', verbose_name='Input Snapshot')),
                ('predicted_result', models.JSONField(blank=True, default=dict, help_text='Structured prediction output', verbose_name='Prediction Results')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Prediction Time')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.exam', verbose_name='Exam')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous predictions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Prediction',
                'verbose_name_plural': 'Predictions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScoreToRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year')),
                ('category', models.CharField(choices=[('general', 'General'), ('sc', 'SC'), ('st', 'ST'), ('obc', 'OBC')], db_index=True, max_length=10, verbose_name='Category')),
                ('score_low', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Score Low')),
                ('score_high', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Score High')),
                ('percentile_low', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentile Low')),
                ('percentile_high', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentile High')),
                ('rank_low', models.PositiveIntegerField(db_index=True, verbose_name='Rank Low')),
                ('rank_high', models.PositiveIntegerField(db_index=True, verbose_name='Rank High')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_to_rank_mappings', to='predictor.exam', verbose_name='Exam')),
            ],
            options={
                'verbose_name': 'Score to Rank Mapping',
                'verbose_name_plural': 'Score to Rank Mappings',
                'ordering': ['exam', '-year', 'category', 'rank_low'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['college', 'degree', 'branch'], name='predictor_c_college_6e7dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'degree'], name='predictor_c_is_acti_b94f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['exam', 'year', 'category', 'opening_rank', 'closing_rank'], name='predictor_c_exam_id_b7b688_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['exam', 'category', 'quota', 'state', 'opening_rank'], name='predictor_c_exam_id_387de2_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['course', 'year', 'category'], name='predictor_c_course__d13867_idx'),
        ),
        migrations.AddIndex(
            model_name='cutoff',
            index=models.Index(fields=['opening_rank', 'closing_rank'], name='predictor_c_opening_10995e_idx'),
        ),
        migrations.AddConstraint(
            model_name='cutoff',
            constraint=models.UniqueConstraint(fields=('exam', 'course', 'year', 'category', 'quota', 'seat_type', 'state'), name='unique_cutoff'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['user', '-timestamp'], name='predictor_p_user_id_2eaa29_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['exam', 'category', 'input_rank'], name='predictor_p_exam_id_67e507_idx'),
        ),
        migrations.AddIndex(
            model_name='scoretorank',
            index=models.Index(fields=['exam', 'year', 'category', 'rank_low', 'rank_high'], name='predictor_s_exam_id_4817f4_idx'),
        ),
        migrations.AddIndex(
            model_name='scoretorank',
            index=models.Index(fields=['exam', 'year', 'category', 'score_low', 'score_high'], name='predictor_s_exam_id_7a463d_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoretorank',
            constraint=models.UniqueConstraint(fields=('exam', 'year', 'category', 'rank_low', 'rank_high'), name='unique_score_rank_mapping'),
        ),
    ]
