# Generated by Django 6.0 on 2025-12-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegemodel',
            old_name='Type',
            new_name='college_type',
        ),
        migrations.RenameField(
            model_name='collegemodel',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='cutoffmodel',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='State',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='collegemodel',
            name='college_name',
        ),
        migrations.AddField(
            model_name='cutoffmodel',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=255),
        ),
    ]
