# Generated by Django 6.0 on 2025-12-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_rename_type_collegemodel_college_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='state',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
