# Generated by Django 6.0 on 2025-12-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_cutoffmodel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreToRankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_low', models.IntegerField()),
                ('score_high', models.IntegerField()),
                ('percentile_low', models.FloatField()),
                ('percentile_high', models.FloatField()),
                ('rank_low', models.IntegerField()),
                ('rank_high', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC')], max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.exammodel')),
            ],
        ),
    ]
