# Generated by Django 6.0 on 2025-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_scoretorankmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoretorankmodel',
            name='percentile_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoretorankmodel',
            name='percentile_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoretorankmodel',
            name='score_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoretorankmodel',
            name='score_low',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
