# Generated by Django 6.0 on 2026-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_scoretorankmodel_percentile_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], max_length=10),
        ),
    ]
