# Generated by Django 5.1.7 on 2026-01-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_alter_cutoffmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='quota',
            field=models.CharField(choices=[('State', 'State'), ('AIQ', 'AIQ'), ('OS', 'OS'), ('GO', 'GO'), ('JK', 'JK'), ('LA', 'LA')], max_length=10),
        ),
    ]
