# Generated by Django 5.1.7 on 2026-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_alter_cutoffmodel_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='quota',
            field=models.CharField(choices=[('State', 'State'), ('AIQ', 'AIQ')], max_length=10),
        ),
    ]
