# Generated by Django 5.1.7 on 2026-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_alter_cutoffmodel_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutoffmodel',
            name='seat_type',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('OPEN (PwD)', 'OPEN (PwD)'), ('OBC-NCL', 'OBC-NCL'), ('OBC-NCL (PwD)', 'OBC-NCL (PwD)'), ('SC', 'SC'), ('SC (PwD)', 'SC (PwD)'), ('ST', 'ST'), ('ST (PwD)', 'ST (PwD)'), ('EWS', 'EWS'), ('EWS (PwD)', 'EWS (PwD)')], default='OPEN', max_length=100),
        ),
    ]
