# Generated by Django 6.0 on 2026-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_cutoffmodel_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS'), ('GEN-PWD', 'GEN-PWD'), ('OBC-NCL-PWD', 'OBC-NCL-PWD'), ('SC-PWD', 'SC-PWD'), ('ST-PWD', 'ST-PWD'), ('EWS-PWD', 'EWS-PWD')], max_length=15),
        ),
    ]
