# Generated by Django 6.0 on 2026-01-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_alter_cutoffmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoffmodel',
            name='quota',
            field=models.CharField(choices=[('State', 'State'), ('AIQ', 'AIQ'), ('AI', 'AI'), ('AP', 'AP'), ('GO', 'GO'), ('HS', 'HS'), ('JK', 'JK'), ('LA', 'LA'), ('OS', 'OS')], max_length=10),
        ),
    ]
